# LAB 2 

In [ ]:
#Sophia Gamarro: 20170356

In [1]:
import numpy as np


In [ ]:
##PROBLEMA 1

In [3]:
M = np.array([
    [1, 1, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 0, 1, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 1],
    [1, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 1, 1, 1],
    [1, 1, 1, 0, 0, 0, 1]
])

M1 = np.array([
    [1, 1, 0, 0, 0, 1, 1],
    [1, 1, 1, 0, 1, 0, 0],
    [0, 1, 1, 1, 1, 0, 0],
    [0, 0, 1, 1, 0, 0, 1],
    [0, 1, 1, 0, 1, 1, 1],
    [1, 0, 0, 0, 1, 1, 1],
    [1, 0, 0, 1, 1, 1, 1]
])

M2 = np.array([
    [1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 1, 1, 1],
])

relacion = lambda mat : print(f'La matriz \n{mat}'
                           f'\nreflexiva: {np.all(np.diagonal(mat))}'
                           f'\nsimétrica: {np.allclose(mat, mat.T)} '
                           f'\ntransitiva: {np.allclose(mat, np.where(mat@mat>1, 1, mat@mat))}')

relacion(M)
relacion(M1)
relacion(M2)

La matriz 
[[1 1 0 0 0 0 1]
 [0 1 1 0 0 1 0]
 [0 0 1 1 0 0 0]
 [0 0 0 1 1 0 1]
 [1 0 0 0 0 1 1]
 [0 0 0 0 1 1 1]
 [1 1 1 0 0 0 1]]
reflexiva: False
simétrica: False 
transitiva: False
La matriz 
[[1 1 0 0 0 1 1]
 [1 1 1 0 1 0 0]
 [0 1 1 1 1 0 0]
 [0 0 1 1 0 0 1]
 [0 1 1 0 1 1 1]
 [1 0 0 0 1 1 1]
 [1 0 0 1 1 1 1]]
reflexiva: True
simétrica: True 
transitiva: False
La matriz 
[[1 1 0 0 0 0 0]
 [1 1 0 0 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 1 1 1]]
reflexiva: True
simétrica: True 
transitiva: True


In [ ]:
#PROBLEMA 2

In [4]:
A = np.arange(5, 9).reshape(2, 2)
print(A)

B = np.arange(-7, -1).reshape(2, 3)
print(B)

C = np.arange(4, 14, 3).reshape(2, 2)
print(C)

D = np.eye(2)
print(D)

E = np.zeros(6).reshape(2, 3)
print(E)

H = np.vstack((np.hstack((A, np.hstack((np.eye(2), np.zeros(6).reshape(2, 3))))), np.hstack((np.eye(2), np.hstack((C, B))))))
print(H)

[[5 6]
 [7 8]]
[[-7 -6 -5]
 [-4 -3 -2]]
[[ 4  7]
 [10 13]]
[[1. 0.]
 [0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 5.  6.  1.  0.  0.  0.  0.]
 [ 7.  8.  0.  1.  0.  0.  0.]
 [ 1.  0.  4.  7. -7. -6. -5.]
 [ 0.  1. 10. 13. -4. -3. -2.]]


In [ ]:
#PROBLEMA 3

In [9]:
A = np.arange(0,24).reshape(4,6)

def rota90(mat):
    print(np.rot90(mat))
rota90(A)

def rota180(mat):
    print(np.rot90(mat,2))
rota180(A)

def rota270(mat):
    print(np.rot90(mat,3))
rota270(A)

# OTRO LADO


def rota90_otro_lado(mat):
    print(np.rot90(mat,1,(1,0)))
rota90_(A)

def rota180_otro_lado(mat):
    print(np.rot90(mat,2,(1,0)))
rota180_(A)

def rota270_otro_lado(mat):
    print(np.rot90(mat,3,(1,0)))
rota270_(A)


[[ 5 11 17 23]
 [ 4 10 16 22]
 [ 3  9 15 21]
 [ 2  8 14 20]
 [ 1  7 13 19]
 [ 0  6 12 18]]
[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
[[18 12  6  0]
 [19 13  7  1]
 [20 14  8  2]
 [21 15  9  3]
 [22 16 10  4]
 [23 17 11  5]]
[[18 12  6  0]
 [19 13  7  1]
 [20 14  8  2]
 [21 15  9  3]
 [22 16 10  4]
 [23 17 11  5]]
[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
[[ 5 11 17 23]
 [ 4 10 16 22]
 [ 3  9 15 21]
 [ 2  8 14 20]
 [ 1  7 13 19]
 [ 0  6 12 18]]


In [ ]:
#PROBLEMA 4

In [11]:
x = np.array([
#    x  a  y  b  z  c  t  d
    [2, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0, 0],
    [-1, 2, 0, 0, 0, 0, 0, 0],
    [0, 0, 2, 1, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, -1, 2, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 1, 0, 0],
    [0, 0, 0, 0, 1, 1, 0, 0],
    [0, 0, 0, 0, -1, 2, 0, 0],
    [0, 0, 0, 0, 0, 0, 2, 1],
    [0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, -1, 2]
])

y = np.array([4, 3, 3, 3, 2, 1, 6, 4, 2, -3, -1, 4]).reshape(12, 1) 

res = np.hstack((
    np.array([
        ['x'],
        ['a'],
        ['y'],
        ['b'],
        ['z'],
        ['c'],
        ['t'],
        ['d']
    ]),
    (np.linalg.lstsq(x, y, rcond=None)[0])
))

print(f'Soluciones: \n{res}')

Soluciones: 
[['x' '1.0000000000000004']
 ['a' '2.0']
 ['y' '1.0000000000000002']
 ['b' '1.0000000000000007']
 ['z' '2.0000000000000004']
 ['c' '2.0000000000000013']
 ['t' '-2.000000000000001']
 ['d' '1.0000000000000004']]
